import Head from 'next/head'
import dynamic from 'next/dynamic'
import * as React from 'react'

const Content = dynamic(() => import('./Content').then((val) => val.Content), {
  ssr: false,
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          width: '100%',
          height: '100%',
          display: 'flex',
          flexDirection: 'column',
        }}
      >
        <Content />
      </main>
    </>
  )
}
